# Generated by Django 5.2.6 on 2025-09-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='major',
            name='coordinator_contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='major',
            name='coordinator_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
