# Generated by Django 5.2.6 on 2025-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_department_head_alter_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Фак', max_length=100)),
                ('description', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
    ]
